import React from 'react';
import { Target, CheckCircle2, Shield, Key, Cpu } from 'lucide-react';

export default function AimSection() {
  return (
    <div>
      <div className="section-header">
        <h2 className="section-title">Message Authentication Code (MAC)</h2>
        <p className="section-subtitle">Experiment: Generation & Verification of MAC tags using Shared Secret Keys</p>
      </div>

      <div className="vlab-card">
        <h3 className="card-title">
          <Target className="card-title-icon" size={22} /> Primary Experiment Aim
        </h3>
        <p style={{ fontSize: '1.05rem', color: '#334155', lineHeight: 1.8 }}>
          The primary objective of this experiment is to implement, analyze, and verify a <strong>Message Authentication Code (MAC)</strong> for arbitrary messages using a shared secret key $K$. Students will explore block-cipher based MAC constructions (<strong>CBC-MAC</strong> and <strong>CMAC - NIST SP 800-38B</strong>) alongside general keyed MAC functions $C(K, M) \rightarrow T$ to evaluate data integrity and origin authentication.
        </p>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '20px', marginTop: '24px' }}>
          <div style={{ background: '#f0f9ff', padding: '20px', borderRadius: '10px', border: '1px solid #bae6fd' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px', color: '#0369a1', fontWeight: '700', marginBottom: '8px' }}>
              <Shield size={20} /> Data Origin Authentication
            </div>
            <p style={{ fontSize: '0.9rem', color: '#0c4a6e' }}>
              Proving that the transmitted payload $M$ was generated by a legitimate sender holding the shared secret key $K$.
            </p>
          </div>

          <div style={{ background: '#f0fdf4', padding: '20px', borderRadius: '10px', border: '1px solid #bbf7d0' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px', color: '#15803d', fontWeight: '700', marginBottom: '8px' }}>
              <CheckCircle2 size={20} /> Data Integrity Verification
            </div>
            <p style={{ fontSize: '0.9rem', color: '#14532d' }}>
              Detecting any unauthorized bit modifications, insertions, or payload alterations introduced by an eavesdropper in transit.
            </p>
          </div>

          <div style={{ background: '#fff7ed', padding: '20px', borderRadius: '10px', border: '1px solid #fed7aa' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px', color: '#c2410c', fontWeight: '700', marginBottom: '8px' }}>
              <Cpu size={20} /> Symmetric Cipher MAC Suite
            </div>
            <p style={{ fontSize: '0.9rem', color: '#7c2d12' }}>
              Utilizing AES-128 block cipher chaining (CBC-MAC) and CMAC subkey derivation ($K_1, K_2$) for fixed-length tag generation.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
